---
aws_region: us-west-2
thepoint_ec2_aws_instance_type: t4g.small
thepoint_ec2_aws_image: ami-0cf467cdd983a5859
net_ipv4: 172.31.0.0/16
subnets:
  a:
    ipv4: 172.31.32.0/20
    ipv6: 2600:1f14:ef5:8802::/64
  b:
    ipv4: 172.31.16.0/20
    ipv6: 2600:1f14:ef5:8801::/64
  c:
    ipv4: 172.31.0.0/20
    ipv6: 2600:1f14:ef5:8800::/64
cw_group_test: thepoint-test
cw_group_prod: thepoint-web
