---
- name: transparent_hugepage
  ansible.builtin.systemd:
    name: disable-transparent-huge-pages
    state: started
    daemon_reload: true
- name: reload_docker
  ansible.builtin.service:
    name: docker
    state: restarted
